version: "3.9"
services:
  # PostgreSQL Database for Keycloak
  postgresql:
    container_name: postgres1
    image: postgres:14.4
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: keycloak

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - "8081:8081"
    command: ["start-dev", "--http-port=8081"]
    depends_on:
      - postgresql

  # PostgreSQL Database for general use
  postgres:
    container_name: db
    image: "postgres:14.4"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/d/esprit/2eme-annee/microservice/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  eurekaserver:
    container_name: eurekaserver
    build:
      context: EurekaSever
    ports:
      - "8761:8761"
    image: "eur"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/


  gateway:
    build:
      context: gatewayserver
    ports:
      - "9999:9999"
    image: "gateway"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/

  # MySQL Database
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql



  # MongoDB Service for Ticket Management
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

networks:
  local:
    name: local
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  mongo_data:
  keycloak_data:
